name: emg
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - aom=3.12.1
  - appnope=0.1.4
  - asttokens=3.0.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - comm=0.2.3
  - contourpy=1.3.1
  - cpython=3.13.9
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - filelock=3.20.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.10.0
  - gettext=0.21.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - importlib-metadata=8.5.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.4
  - libiconv=1.16
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libtiff=4.7.0
  - libtorch=2.7.0
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.2.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nomkl=3.0
  - numexpr=2.14.1
  - numpy=2.3.4
  - numpy-base=2.3.4
  - openssl=3.6.0
  - opentelemetry-api=1.37.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.2.0
  - python=3.13.9
  - python-dateutil=2.9.0post0
  - python-gil=3.13.9
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytorch=2.7.0
  - pytz=2025.2
  - pyzmq=27.1.0
  - readline=8.3
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.5.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - sympy=1.14.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /opt/miniconda3/envs/emg
